=== {learning-goals}

// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: Dies ist das erste Lernziel in Kapitel 4, das mit xyz

Hier wird beschrieben, was Teilnehmer:innen in diesem Lernziel lernen sollen. Das kann in Prosa-Text
in ganzen Sätzen oder in Aufzählungen mit Unterpunkten erfolgen. Dabei kann auch unterschieden werden,
wie wichtig einzelne Aspekte des Lernziels sind. Es kann hier bereits auf Literatur verwiesen werden.

* Erstes Teilziel
* Zweites Unterthema
* Dritter Aspekt

[[LZ-6-2]]
==== LZ 6-2: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.

// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: Security as a Quality in Embedded Systems

Participants understand security as a system quality and its relation to other quality requirements.
Participants understand security as a quality in the context of ISO 25010 and the relation of these
qualities to the threat modeling analysis technique STRIDE.
Participants understand that embedded security is a cross-cutting concern, that needs to be
addressed at the system, hardware and software level and can not be solved only in software.

Participants understand, that the physical access users can gain to the devices pose an
uncircumventable risk, therefore it should be considered that the compromise of single device should
not compromise all products (e.g., when the same symmetric key is used in all devices).

[[LG-6-2]]
==== LG 6-2: Safety and Security

Participants understand that embedded systems can influence the physical world and pose additional
safety risks that need to be addressed.

[[LG-6-3]]
==== LG 6-3: Guiding Principles

Participants understand that good software engineering practices help designing a more secure
system.
They are able to explain why a modular design supports achieving security goals.

In addition, participants know design principles to building secure systems and how they are
reflected in embedded systems, examples include:

* Defense in depth (e.g., encrypted firmware with additional hardware readout-protection),
* Least-privilege Principle (e.g., reduced access to peripherals or enforcement of memory regions),
* Data Minimization (e.g., which information to log or transmit),
* Self-protection (e.g., voltage-glitch detection, secure states),
* (No) Security by Obscurity
* Input and Output Validation

[[LG-6-4]]
==== LG 6-4: Resource Restrictions

Participants understand that resource constraints limit the solution space for embedded systems.
Examples of such limitations are:

* Space, Computation Power, or Energy: The implementability of cryptographic algorithms might be
limited by available peripherals, or the speed with which algorithms can be computed. Reliable update
strategies, such as AB-Partitioning might not be implementable.
* Networking and Connectivity: The unavailability of an internet connection, a trusted time provider,
or other communication paths might hinder updateability, usage of time reliant authentication
mechanisms or ensuring secure, auditable logging.
* Memory: Different types of memories are used, which might limit how often they can be overwritten.
This can be used as a benefit, e.g., for One-Time Programming Keys, but also cause drawbacks in case
these keys are compromised. Enforcement of roll-back protections through hardware fuses might be
limited by the amount of available fuses.

[[LG-6-5]]
==== LG 6-5: Software Updates

Participants understand the need for software updates and the challenges deploying updates to embedded
devices pose.
Participants know the security trade-off of updatable devices, as this mechanism increase the devices
attack surface.
Participants know possible solutions to securely deploy updates to embedded devices (e.g., signed
and encrypted firmware packages, secure version numbers)

[[LG-6-6]]
==== LG 6-6: Secure Implementation

Participants understand how a well engineered implementation supports the security goals.
Participants know standards and guidelines to reduce the likelihood of introducing defects during
the implementation such as MISRA, CERT Coding Guidelines or OWASP's Secure Coding Practices.
// end::EN[]
