// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

Das Modul präsentiert den Teilnehmerinnen und Teilnehmern {curriculum-name} als …
Am Ende des Moduls kennen die Teilnehmerinnen und Teilnehmer … und können …
// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

The module EMBEDDEDSEC conveys the methods to participants to design an embedded system architecture that
reflects their security goals. Building on the concepts of the foundation level, the module
introduces participants to analysis methods to identify protection worthy assets and derive security
goals for embedded systems. It presents qualities, design patterns and technologies which help in
achieving security goals and familiarizes participants with common attack patterns. Finally
techniques to verify and validate security properties are presented. At the end of the module the
participants know approaches to design embedded architectures with security as a quality in mind,
and are able to identify security risks and select suitable control measures.
// end::EN[]
