=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Dies ist das erste Lernziel, in Kategorie xy

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Definition of Security

Participants know a definition of security and understand it as a quality of the system.
Participants understand the relationship and trade-offs to other quality attributes.

ifeval::["{suffix}" == "EMBEDDEDSEC"]
Definitions can be found for example in ISO/IEC 25010, ISO/SAE 21434 and IEC 62443.
endif::[]

[[LG-1-2]]
==== LG 1-2: Security Properties

Participants know the security properties of the universal triad: confidentiality, integrity and
availability. In addition they know additional common properties such as authentication, authorization
and non-repudiation.

[[LG-1-3]]
==== LG 1-3: Security Lifecycles
Participants understand, that security must be considered in the whole product lifecycle and not
just for the development phase.
Participants understand that maintaining security requires participation and consideration of all stakeholders.
Participants know the typical lifecycle phases (conception, development, production, operation and maintenance, and decommission).
Participants know at least one example of a security product lifecycle.

ifeval::["{suffix}" == "EMBEDDEDSEC"]
Examples of security product lifecycles are presented ISO/SAE 21434, the Microsoft Security Development
Lifecycle and NIST's Secure Software Development Framework.
endif::[]

[[LG-1-4]]
==== LG 1-4: Security Regulations and standards
Participants understand the difference between regulations, standards and guidelines.
Participants know examples of regulations, standards and guidelines regarding security.

ifeval::["{suffix}" == "EMBEDDEDSEC"]
Example of security regulations, standards and guidelines  are UN R 155, UN R 156, ISO/SAE 21434,
FDA Guidelines, NIST Standards such as SP800, IEC 62443, IEC 80001-5-1, IEC 60601-4-5, ISO 270xx and
ETSI EN 303 645.
endif::[]

// end::EN[]
